## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("C:/Users/AlexPapa/Desktop/Repos/World_Weather_Analysis/Weather_Database/Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID             City Country  Max Temp Current Description      Lat  \
0        3  Arraial Do Cabo      BR     75.16       broken clouds -22.9661   
1        4            Vaini      TO     75.36       broken clouds -21.2000   
2        5          Rikitea      PF     73.11     overcast clouds -23.1203   
3        7  Arraial Do Cabo      BR     75.16       broken clouds -22.9661   
4        8          Mataura      PF     73.11     overcast clouds -23.1203   

        Lng           Hotel Name  
0  -42.0278  Pousada Porto Praia  
1 -175.2000  Keleti Beach Resort  
2 -134.9692      People ThankYou  
3  -42.0278  Pousada Porto Praia  
4 -134.9692      People ThankYou

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [12]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

start_city = "Chibombo"
end_city = "Chibombo"
city1 = "Nampula"
city2 = "Bulawayo"
city3 = "Orapa"

vacation_start = vacation_df.loc[vacation_df["City"] == start_city]
vacation_end = vacation_df.loc[vacation_df["City"] == end_city]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == city1]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == city2] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == city3] 

In [13]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]
start, end, stop1, stop2, stop3

(array([-10.2621,  29.9271]),
 array([-10.2621,  29.9271]),
 array([-17.8786,  36.8883]),
 array([-21.05  ,  31.6667]),
 array([-18.5278,  25.627 ]))

In [14]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
travel_route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(travel_route)
fig


Figure(layout=FigureLayout(height='420px'))

In [8]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID      City Country  Max Temp Current Description      Lat      Lng  \
0     1880  Chibombo      ZM     74.66     overcast clouds -10.2621  29.9271   
1     1794   Fomboni      KM     77.59    scattered clouds -11.3847  43.2844   
2     1898   Nampula      MZ     76.95    scattered clouds -17.8786  36.8883   
3     1410  Bulawayo      ZW     78.71           clear sky -21.0500  31.6667   

                              Hotel Name  
0  MR.C SIMON CHABALA (Maje, Home Place)  
1                              Foyer ADM  
2                         Hotel Flamingo  
3                 Clevers Hotel Chiredzi

In [9]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [10]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure


In [11]:
fig

Figure(layout=FigureLayout(height='420px'))